# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.mathtest_pb2 as mathtest__pb2


class MathTestStub(object):
  """Defines the service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendRequest = channel.unary_unary(
        '/mathtest.MathTest/sendRequest',
        request_serializer=mathtest__pb2.MathRequest.SerializeToString,
        response_deserializer=mathtest__pb2.MathReply.FromString,
        )


class MathTestServicer(object):
  """Defines the service
  """

  def sendRequest(self, request, context):
    """Function invoked to send the request
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MathTestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendRequest': grpc.unary_unary_rpc_method_handler(
          servicer.sendRequest,
          request_deserializer=mathtest__pb2.MathRequest.FromString,
          response_serializer=mathtest__pb2.MathReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mathtest.MathTest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
