# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import macOS.protos.helloworld_pb2 as helloworld__pb2


class TestServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello_request = channel.unary_unary(
        '/helloworld.TestServer/hello_request',
        request_serializer=helloworld__pb2.HelloMessage.SerializeToString,
        response_deserializer=helloworld__pb2.Reply.FromString,
        )


class TestServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hello_request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello_request': grpc.unary_unary_rpc_method_handler(
          servicer.hello_request,
          request_deserializer=helloworld__pb2.HelloMessage.FromString,
          response_serializer=helloworld__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.TestServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
